apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-script
  namespace: monitoring
data:
  locustfile.py: |
    from locust import HttpUser, task, between

    class MyUser(HttpUser):
        wait_time = between(1, 2)

        @task
        def hello_world(self):
            self.client.get("/hello")


