apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: locust-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: eks-efs


